# DizzyoOS Pacman Configuration

[options]
HoldPkg     = pacman
CleanMethod = KeepInstalled
Architecture = auto
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 5

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# DizzyoOS Repositories
[dizzyo-core]
SigLevel = PackageRequired DatabaseOptional
Server = https://mirror.dizzyo-os.org/$repo/$arch

[dizzyo-extra]
SigLevel = PackageRequired DatabaseOptional
Server = https://mirror.dizzyo-os.org/$repo/$arch

[dizzyo-gaming]
SigLevel = PackageRequired DatabaseOptional
Server = https://mirror.dizzyo-os.org/$repo/$arch

[dizzyo-unstable]
SigLevel = PackageRequired DatabaseOptional
Server = https://mirror.dizzyo-os.org/$repo/$arch
